services:
  app:
    build: .
    ports:
      - "5000:5000"

    depends_on:
      - mysql
 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: company
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:  
